name: Deploy Documentation

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment on

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Build and Deploy
      run: |
        # Replace 'docs' with the actual folder where your documentation is generated
        cp -r docs/* $GITHUB_WORKSPACE

        git checkout --orphan gh-pages
        git --work-tree=$GITHUB_WORKSPACE add --all
        git --work-tree=$GITHUB_WORKSPACE commit -m "Deploy documentation to GitHub Pages"
        git push origin HEAD:gh-pages --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
