name: Deploy Documentation

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deployment on
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Install Doxygen
      run: sudo apt-get install doxygen

    - name: Generate Doxygen Documentation
      run: doxygen Doxyfile  # Assuming your Doxygen configuration file is named Doxyfile
    
    - name: Build and Deploy
      run: |
        cp -r html/* $GITHUB_WORKSPACE

        git checkout --orphan gh-pages
        git --work-tree=$GITHUB_WORKSPACE add --all
        git --work-tree=$GITHUB_WORKSPACE commit -m "Deploy documentation to GitHub Pages"
        git push origin HEAD:gh-pages --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
